ISHAuditCore/Controllers/SignUpController.cs
using System.Text.RegularExpressions;
using ISHAuditCore.Context;
using ISHAuditCore.Migrations.Model;
using ISHAuditCore.Models;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using user_info = ISHAuditCore.Entities.user_info;

namespace ISHAuditCore.Controllers
{
    public class SignUpController : baseController
    {
        private readonly UserEditService _userEditService;
        private readonly ISHAuditDbcontext _db;
        
        // 控制器建構函數，注入 SignUpService 和其他依賴
        public SignUpController(ISHAuditDbcontext dbContext, Authority authorityClass, UserEditService userEditService)
            : base(dbContext, authorityClass,userEditService) // 呼叫 baseController 的構造函數
        {
            _db = dbContext;
            _userEditService = userEditService ?? throw new ArgumentNullException(nameof(userEditService));
        }

        // 頁面方法
        public IActionResult Index()
        {
            var enterprises = _userEditService.GetEnterpriseList();
            ViewBag.EnterpriseJson = JsonConvert.SerializeObject(enterprises);
            return View();
        }
        
        
        /// <summary>
        /// 用於處理使用者註冊的動作，並進行密碼驗證、企業相關資訊處理和儲存註冊資料到資料庫。
        /// </summary>
        /// <param name="post">包含使用者輸入的註冊資訊的表單資料。</param>
        /// <returns>回傳一個包含註冊結果的 JSON 響應，若成功註冊則回傳成功訊息，若有錯誤則回傳錯誤訊息。</returns>
        /// <remarks>
        /// 此方法的主要功能為：
        /// 
        /// 1. 驗證密碼格式是否符合要求（至少 8-20 位，包含大小寫字母和數字）。
        /// 2. 根據使用者輸入處理企業（enterprise）、公司（company）、工廠（factory）的 ID 資訊，若沒有輸入則設為 null。
        /// 3. 生成使用者的權限資訊（Audit、KPI、Sys、Org）並序列化為 JSON 字符串保存。
        /// 4. 檢查是否已存在相同帳號名稱的使用者，若存在則回傳錯誤訊息。
        /// 5. 將新註冊的使用者資訊（包括帳號、加密後的密碼、暱稱、權限等）儲存到資料庫中。
        /// 6. 註冊成功後回傳成功訊息。
        /// 
        /// <example>
        /// 密碼格式驗證的正則表達式為：^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,20}$，至少要包含一個小寫字母、一個大寫字母和一個數字，長度為 8 至 20 位。
        /// </example>
        /// </remarks>
        /// <exception cref="ArgumentException">如果使用者帳號已經存在，將回傳錯誤訊息。</exception>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(IFormCollection post)
        {
            if (!Regex.IsMatch(post["password"], @"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,20}$"))
            {
                var errorResponse = new { error = "密碼不符合規則:" + post["password"] + "\n 請最少輸入8-20位大小寫混和英文與數字" };
                return Json(errorResponse);
            }
            else
            {
                byte[] salt = new byte[128 / 8];
                string username = post["username"];
                string password = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                    password: post["password"],
                    salt: salt,
                    prf: KeyDerivationPrf.HMACSHA1,
                    iterationCount: 10000,
                    numBytesRequested: 256 / 8));
                string nickname = post["nickname"];
                Nullable<Int16> enterpriseId = null;
                Nullable<Int16> companyId = null;
                Nullable<Int16> factoryId = null;
                if (post["enterprise_id"] != "" || post["company_id"] != "" || post["factory_id"] != "")
                {
                    if (post["enterprise_id"] != "")
                    {
                        enterpriseId = Convert.ToInt16(post["enterprise_id"]);
                    }

                    if (post["company_id"] != "")
                    {
                        companyId = Convert.ToInt16(post["company_id"]);
                    }

                    if (post["factory_id"] != "")
                    {
                        factoryId = Convert.ToInt16(post["factory_id"]);
                    }
                }


                // Access specific fields
                string audit = post["Audit"];
                string kpi = post["KPI"];
                string sys = post["Sys"];
                string org = post["Org"];

                Dictionary<string, string> values = new Dictionary<string, string>
                {
                    { "Audit", audit },
                    { "KPI", kpi },
                    { "Sys", sys },
                    { "Org", org }
                };
                string authority = JsonConvert.SerializeObject(values);

                
                if (_db.user_infos.Any(u => u.username == username))
                {
                    var errorResponse = new { error = "此帳號已有人使用" };
                    return Json(errorResponse);
                }

                string formattedDate = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss.ffffff");
                DateTime? parsedDate = DateTime.TryParse(formattedDate, out DateTime result)
                    ? (DateTime?)result
                    : null;
                user_info newUser = new user_info()
                {
                    username = username,
                    password = password,
                    nickname = nickname,
                    enterprise_id = enterpriseId,
                    company_id = companyId,
                    factory_id = factoryId,
                    authority = authority,
                    created_at = parsedDate,
                };

                _db.user_infos.Add(newUser);
                _db.SaveChanges();

                var successResponse = new { message = "註冊成功" };
                return Ok(successResponse);
                
            }
        }
    }
}

ISHAuditCore/Views/SignUp/index.cshtml
@using Newtonsoft.Json
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    ViewBag.Title = "新增帳號";
}

@section css{
    <link rel="stylesheet" href="~/css/loading.css">
}

@section js{

}

@section page_title{

}

@section location{
    <li class="breadcrumb-item">@Html.ActionLink("首頁", "Index", "Home")</li>
    <li class="breadcrumb-item active">@Html.ActionLink("新增帳號", "Index", "SignUp")</li>
}


<div class="container-fluid">
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">建立人員帳號</h3>
        </div>
        <form id="signup-form" action="/SignUp/Index" method="post" class="mt-3">
            @Html.AntiForgeryToken()
            <div class="card-body">
                <div class="row">
                    <div class="col-12 col-sm-3">
                        <div class="form-group">
                            <label for="username" class="form-label">帳號：</label>
                            <input type="text" class="form-control" id="username" name="username">
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 col-sm-3">
                        <div class="form-group">
                            <label for="password" class="form-label">密碼：</label>
                            <input type="password" class="form-control" id="password" name="password"
                                   pattern='^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,20}$'
                                   title="請填入8~20位英文(必須含大寫)數字混和密碼">
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 col-sm-3">
                        <div class="form-group">
                            <label for="nickname" class="form-label">名字：</label>
                            <input type="text" class="form-control" id="nickname" name="nickname">
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 col-sm-3">
                        <div class="form-group">
                            <label for="enterprise_id" class="form-label">企業：</label>
                            <select id="enterprise_id" name="enterprise_id" class="form-control select2" style="width: 100%;">
                                <option value="">-- 請選擇 --</option>
                                @* 企業選項將由 JavaScript 動態更新 *@
                            </select>
                        </div>
                    </div>

                    <div class="col-12 col-sm-3">
                        <div class="form-group">
                            <label for="company_id" class="form-label">公司：</label>
                            <select id="company_id" name="company_id" class="form-control select2" style="width: 100%;">
                                <option value="">-- 請選擇 --</option>
                                @* 公司選項將由 JavaScript 動態更新 *@
                            </select>
                        </div>
                    </div>

                    <div class="col-12 col-sm-3">
                        <div class="form-group">
                            <label for="factory_id" class="form-label">工廠：</label>
                            <select id="factory_id" name="factory_id" class="form-control select2" style="width: 100%;">
                                <option value="">-- 請選擇 --</option>
                                @* 工廠選項將由 JavaScript 動態更新 *@
                            </select>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 col-sm-12">
                        <label class="form-label">Audit權限：</label>
                        <div class="form-check">
                            <fieldset>
                                <input class="form-radio-input" type="radio" name="Audit" value="admin">
                                <label class="form-radio-label">Admin</label>
                                <input class="form-radio-input" type="radio" name="Audit" value="power">
                                <label class="form-radio-label">Power</label>
                                <input class="form-radio-input" type="radio" name="Audit" value="operator">
                                <label class="form-radio-label">Operator</label>
                                <input class="form-radio-input" type="radio" name="Audit" value="none">
                                <label class="form-radio-label">None</label>
                            </fieldset>
                        </div>

                        <label class="form-label">KPI權限：</label>
                        <div class="form-check">
                            <fieldset>
                                <input class="form-radio-input" type="radio" name="KPI" value="admin">
                                <label class="form-radio-label">Admin</label>
                                <input class="form-radio-input" type="radio" name="KPI" value="power">
                                <label class="form-radio-label">Power</label>
                                <input class="form-radio-input" type="radio" name="KPI" value="operator">
                                <label class="form-radio-label">Operator</label>
                                <input class="form-radio-input" type="radio" name="KPI" value="none">
                                <label class="form-radio-label">None</label>
                            </fieldset>
                        </div>

                        <label class="form-label">Sys權限：</label>
                        <div class="form-check">
                            <fieldset>
                                <input class="form-radio-input" type="radio" name="Sys" value="admin">
                                <label class="form-radio-label">Admin</label>
                                <input class="form-radio-input" type="radio" name="Sys" value="none">
                                <label class="form-radio-label">None</label>
                            </fieldset>
                        </div>

                        <label class="form-label">Org權限：</label>
                        <div class="form-check">
                            <fieldset>
                                <input class="form-radio-input" type="radio" name="Org" value="admin">
                                <label class="form-radio-label">Admin</label>
                                <input class="form-radio-input" type="radio" name="Org" value="factory">
                                <label class="form-radio-label">Factory</label>
                                <input class="form-radio-input" type="radio" name="Org" value="manager">
                                <label class="form-radio-label">Manager</label>
                                <input class="form-radio-input" type="radio" name="Org" value="enterprise">
                                <label class="form-radio-label">Enterprise</label>
                                <input class="form-radio-input" type="radio" name="Org" value="company">
                                <label class="form-radio-label">Company</label>
                            </fieldset>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card-footer">
                <button class="btn btn-primary">註冊</button>
            </div>
        </form>
    </div>
</div>

@section scripts
{
    <script>
    $(document).ready(function () {
        // 將 JSON 字符串轉換為 JavaScript 對象
        var enterprises = JSON.parse(@Html.Raw(JsonConvert.SerializeObject(ViewBag.EnterpriseJson)));
        var companies = JSON.parse(@Html.Raw(JsonConvert.SerializeObject(ViewBag.CompanyJson)));
        var factories = JSON.parse(@Html.Raw(JsonConvert.SerializeObject(ViewBag.FactoryJson)));

        // 調試輸出數據
        console.log("Enterprises:", enterprises);
        console.log("Companies:", companies);
        console.log("Factories:", factories);

        // 填充企業選單
        var enterpriseSelect = $('#enterprise_id');
        enterpriseSelect.empty().append('<option value="">-- 請選擇 --</option>');
        enterprises.forEach(function (enterprise) {
            enterpriseSelect.append('<option value="' + enterprise.Id + '">' + enterprise.Name + '</option>');
        });

        // 當企業選擇改變時，從企業的 Child 中提取公司
        $('#enterprise_id').change(function () {
            var selectedEnterpriseId = $(this).val();
            var companySelect = $('#company_id');
            var factorySelect = $('#factory_id');

            console.log("Selected Enterprise ID:", selectedEnterpriseId);

            // 清空公司和工廠選單
            companySelect.empty().append('<option value="">-- 請選擇 --</option>');
            factorySelect.empty().append('<option value="">-- 請選擇 --</option>');

            // 找到選擇的企業，然後直接使用 Child 屬性中的公司列表
            var selectedEnterprise = enterprises.find(enterprise => enterprise.Id == selectedEnterpriseId);

            // 調試：檢查選擇的企業及其 Child 屬性
            console.log("Selected Enterprise:", selectedEnterprise);
            if (selectedEnterprise && selectedEnterprise.Child && selectedEnterprise.Child.length > 0) {
                selectedEnterprise.Child.forEach(function (company) {
                    console.log("Adding Company:", company);  // 調試：檢查正在添加的公司
                    companySelect.append('<option value="' + company.Id + '">' + company.Name + '</option>');
                });
            } else {
                console.warn("No companies found for the selected enterprise. Check if Child contains companies.");
            }
        });

        // 當公司選擇改變時，從公司的 Child 中提取工廠
        $('#company_id').change(function () {
            var selectedCompanyId = $(this).val();
            var factorySelect = $('#factory_id');

            console.log("Selected Company ID:", selectedCompanyId);

            // 清空工廠選單
            factorySelect.empty().append('<option value="">-- 請選擇 --</option>');

            // 找到選擇的公司，然後直接使用 Child 屬性中的工廠列表
            var selectedCompany = companies.find(company => company.Id == selectedCompanyId);

            // 調試：檢查選擇的公司及其 Child 屬性
            console.log("Selected Company:", selectedCompany);
            if (selectedCompany && selectedCompany.Child && selectedCompany.Child.length > 0) {
                selectedCompany.Child.forEach(function (factory) {
                    console.log("Adding Factory:", factory);  // 調試：檢查正在添加的工廠
                    factorySelect.append('<option value="' + factory.Id + '">' + factory.Name + '</option>');
                });
            } else {
                console.warn("No factories found for the selected company. Check if Child contains factories.");
            }
        });
    });

    $(document).ready(function() {
        $("#signup-form").submit(function(event) {
            event.preventDefault(); // 阻止表单的默認提交行為
            post(); // 調用 post 函数以進行異步提交
        });
    });

    $(document).ready(function () {
        document.forms['signup-form'].reset();
    });

    function post() {
        $.ajax({
            type: "POST",
            url: "/SignUp/Index",
            // 註冊頁面url
            data: $("#signup-form").serialize(),
            // 使用表單id獲取數據
            success:function (data) {
                if (data.error) {
                    // 顯示錯誤訊息
                    alert(data.error);
                } else if (data.message) {
                    // 顯示成功訊息
                    alert(data.message);
                }
            },
            error: function (xhr, status, error) {
                console.error(error);
            },
        });
    }
</script>
}